{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e5dc35c9-d2da-4335-98e0-2eb5d4ef0036",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "from sklearn.tree import DecisionTreeClassifier\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.metrics import classification_report\n",
    "\n",
    "attendance_df = pd.read_csv(\"attendance_logs.csv\")\n",
    "events_df = pd.read_csv(\"event_participation.csv\")\n",
    "lms_df = pd.read_csv(\"lms_usage.csv\")\n",
    "\n",
    "st.title(\"📊 Smart Campus Insights\")\n",
    "st.sidebar.header(\"🔍 Filters\")\n",
    "\n",
    "students = attendance_df['StudentID'].unique()\n",
    "selected_students = st.sidebar.multiselect(\"Select Roll.no of Student\", students, default=students)\n",
    "\n",
    "filtered_attendance = attendance_df[attendance_df['StudentID'].isin(selected_students)]\n",
    "filtered_events = events_df[events_df['StudentID'].isin(selected_students)]\n",
    "filtered_lms = lms_df[lms_df['StudentID'].isin(selected_students)]\n",
    "\n",
    "st.subheader(\"📋 Attendance Trends\")\n",
    "attendance_summary = filtered_attendance.groupby(['Date', 'Status']).size().unstack(fill_value=0)\n",
    "st.line_chart(attendance_summary)\n",
    "\n",
    "st.subheader(\"🎓 Event Participation\")\n",
    "event_counts = filtered_events['EventName'].value_counts()\n",
    "st.bar_chart(event_counts)\n",
    "\n",
    "st.subheader(\"💻 LMS Usage Patterns\")\n",
    "lms_summary = filtered_lms.groupby('StudentID')[['SessionDuration', 'PagesViewed']].mean()\n",
    "st.dataframe(lms_summary)\n",
    "\n",
    "st.subheader(\"🤖 Predict Student Engagement Risk\")\n",
    "\n",
    "ml_data = pd.merge(attendance_df.groupby('StudentID')['Status'].apply(lambda x: (x == 'Absent').mean()).reset_index(name='AbsenceRate'),\n",
    "                   lms_df.groupby('StudentID')[['SessionDuration', 'PagesViewed']].mean().reset_index(),\n",
    "                   on='StudentID')\n",
    "\n",
    "ml_data['Engagement'] = (ml_data['AbsenceRate'] < 0.2).astype(int)\n",
    "\n",
    "X = ml_data[['AbsenceRate', 'SessionDuration', 'PagesViewed']]\n",
    "y = ml_data['Engagement']\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)\n",
    "model = DecisionTreeClassifier()\n",
    "model.fit(X_train, y_train)\n",
    "y_pred = model.predict(X_test)\n",
    "\n",
    "st.text(\"Model Performance:\")\n",
    "st.text(classification_report(y_test, y_pred))\n",
    "\n",
    "st.subheader(\"📈 Predict Engagement for New Student\")\n",
    "absence_rate = st.number_input(\"Absence Rate (0 to 1)\", min_value=0.0, max_value=1.0, value=0.1)\n",
    "session_duration = st.number_input(\"Average Session Duration (minutes)\", min_value=0.0, value=30.0)\n",
    "pages_viewed = st.number_input(\"Average Pages Viewed\", min_value=0.0, value=10.0)\n",
    "\n",
    "if st.button(\"Predict Engagement\"):\n",
    "    prediction = model.predict([[absence_rate, session_duration, pages_viewed]])\n",
    "    result = \"Engaged\" if prediction[0] == 1 else \"At Risk\"\n",
    "    st.success(f\"Predicted Engagement Status: {result}\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
